### ISSUE TITLE
This is a copy of another theme

### ISSUE THREAD

**Issue by khaledmoayad** [sandarutharuneth/spicetify-transparent#1]
this is a copy of [Bloom](https://github.com/nimsandu/spicetify-bloom) by @nimsandu

**Comment by sandarutharuneth** [comment]
Yeah we know that and original author have been credited. New themes coming through this with new plugins and new UI. You can can wait to see the results if you want to. Have a nice day :)

**Comment by nimsandu** [comment]
@khaledmoayad @sandarutharuneth 

Better things always need a proper foundation. Yah, this is a copy of my open-source theme . But im pretty sure that the final output of this theme will be way more user friendly and way more consistent theme. 

Great things takes time,
But by the time this copy become an identical theme. Im sure this theme is going to be one of the best themes in spicetify theme collection.

Thank you both for mentioning me.
@khaledmoayad  I really appreciate you

And @sandarutharuneth i wish you the very best on this project 

Regards 
Nimsandu Kottage

**Comment by sandarutharuneth** [comment]
@nimsandu 

Thanks for Taking little time to talk about this. And yeah I'm really grateful for the foundation code of yours and I'm sure there will be much more changes on this theme with plugins in near future. Good luck with everything and wishing you the best for all your projects and thanks again for the main code. 

Cheers,
Sandaru Tharuneth.

**Comment by khaledmoayad** [comment]
Happy i could clear things up :)
